name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Get minify
        run: wget -qO- https://github.com/tdewolff/minify/releases/download/v2.12.7/minify_linux_amd64.tar.gz | tar -xz
      - name: Set version
        run: |
          echo "${GITHUB_REF_NAME}" > version
          cat conf.py
      - name: Build pages
        run: sh ./buildAll.sh
      - name: Minify
        run: ./minify -v -r --sync -o Help/ _build
      - name: Create archive
        run: |
          zip -r archive.zip Help \
            -x Help/404.html Help\en\404.html Help/index.html **/sitemap.xml **/.doctrees/** **/objects.inv
      - name: Create archive (en)
        run: |
          zip -r en.zip Help/en -x **/sitemap.xml **/.doctrees/** **/objects.inv
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: archive.zip
      - name: Upload artifact (en)
        uses: actions/upload-artifact@v3
        with:
          name: English
          path: en.zip
      - name: Rename directory
        run: mv Help help_pages
      - name: Add to build folder
        run: cp -r _add_to_build/* help_pages
      - name: Configure GitHub Pages
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/configure-pages@v3
      - name: Upload pages
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: Help
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 'automation-test/package-lock.json'
      - name: Test
        run: |
          npm ci
          npm start
        working-directory: automation-test
      - name: Publish asset
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          files: archive.zip
  deploy:
    if: github.ref_type == 'tag'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get gitleaks
      run: |
        wget -qO- https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz | tar xvz
    - name: Check for secrets
      run: |
        ./gitleaks detect -v --redact