name: CI

on:
  push:
    branches:
      - '*'
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build pages
        run: sh ./buildAll.sh
      - name: Get minify
        run: wget -qO- https://github.com/tdewolff/minify/releases/download/v2.12.7/minify_linux_amd64.tar.gz | tar -xz
      - name: Minify
        run: ./minify -v -r --sync -o _minified/ _build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _minified
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            _minified/**
            !404.html
            !google97d4e1b665179c67.html
            !index.html
            !**/*.xml
            !**/.doctrees/**
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
